import type { SeedKata } from "../types/editor";

/** Lookup key for LEETCODE_NUMBERS: a plain, greppable space between language
 * and name. */
function lcKey(language: string, name: string): string {
  return `${language} ${name}`;
}

/**
 * LeetCode problem numbers for seed katas, keyed by `${language} ${name}`.
 *
 * Authoritative source for a kata's LeetCode number — the DB leetcode_number
 * column and the list-view badge both derive from it. Katas that are not
 * LeetCode problems (algorithm drills, runner error fixtures) are intentionally
 * absent and resolve to null.
 *
 * When adding a LeetCode-based seed kata, add its number here too.
 */
export const LEETCODE_NUMBERS: Record<string, number> = {
  "javascript 3Sum": 15,
  "javascript Add Two Numbers": 2,
  "javascript Balanced Parentheses": 20,
  "javascript Best Time to Buy and Sell Stock": 121,
  "javascript Binary Search": 704,
  "javascript Binary Search Find First": 34,
  "javascript Binary Search Find Last": 34,
  "javascript Binary Tree BFS": 102,
  "javascript Build Adjacency List": 133,
  "javascript Build Prefix Sum": 1480,
  "javascript Climbing Stairs": 70,
  "javascript Copy List with Random Pointer": 138,
  "javascript Count Set Bits": 191,
  "javascript DFS Inorder Traversal": 94,
  "javascript DFS Postorder Traversal": 145,
  "javascript DFS Preorder Traversal": 144,
  "javascript Find the Duplicate Number": 287,
  "javascript FizzBuzz": 412,
  "javascript Frequency Count": 1207,
  "javascript Graph DFS": 323,
  "javascript Kadane's Algorithm": 53,
  "javascript Linked List Cycle": 141,
  "javascript Linked List Traversal": 234,
  "javascript Lomuto Partition": 912,
  "javascript Longest Common Subsequence": 1143,
  "javascript Matrix BFS": 1091,
  "javascript Matrix DFS": 200,
  "javascript Merge Intervals": 56,
  "javascript Merge Sort": 912,
  "javascript Merge Sorted Arrays": 88,
  "javascript Min Heap": 703,
  "javascript Monotonic Stack": 496,
  "javascript Most Frequent Element": 347,
  "javascript Permutation in String": 567,
  "javascript Permutations": 46,
  "javascript Queue from Stacks": 232,
  "javascript Quick Sort": 912,
  "javascript Range Sum Query": 303,
  "javascript Remove Nth Node From End of List": 19,
  "javascript Reverse Linked List (Iterative)": 206,
  "javascript Reverse Linked List (Recursive)": 206,
  "javascript Rotate Image": 48,
  "javascript Search a 2D Matrix": 74,
  "javascript Single Number XOR": 136,
  "javascript Sliding Window Max Sum": 2461,
  "javascript Subsets": 78,
  "javascript Time Based Key-Value Store": 981,
  "javascript Topological Sort": 210,
  "javascript Trie": 208,
  "javascript Two Pointer Remove Dupes": 26,
  "javascript Two Sum": 1,
  "javascript Two Sum II - Input Array Is Sorted": 167,
  "javascript Union Find": 684,
  "python 3Sum": 15,
  "python Add and Search Word": 211,
  "python Alien Dictionary": 269,
  "python Balanced Binary Tree": 110,
  "python Balanced Parentheses": 20,
  "python Best Time to Buy and Sell Stock": 121,
  "python Best Time to Buy and Sell Stock With Cooldown": 309,
  "python Binary Search (Iterative)": 704,
  "python Binary Search (Recursive)": 704,
  "python Binary Search Find First": 34,
  "python Binary Search Find Last": 34,
  "python Binary Tree BFS": 102,
  "python Binary Tree Inorder (Iterative)": 94,
  "python Binary Tree Inorder (Recursive)": 94,
  "python Binary Tree Level Order Traversal": 102,
  "python Binary Tree Maximum Path Sum": 124,
  "python Binary Tree Postorder (Iterative)": 145,
  "python Binary Tree Postorder (Recursive)": 145,
  "python Binary Tree Preorder (Iterative)": 144,
  "python Binary Tree Preorder (Recursive)": 144,
  "python Binary Tree Right Side View": 199,
  "python Build Adjacency List": 133,
  "python Build Prefix Sum": 1480,
  "python Burst Balloons": 312,
  "python Car Fleet": 853,
  "python Cheapest Flights Within K Stops": 787,
  "python Climbing Stairs (Iterative)": 70,
  "python Climbing Stairs (Recursive)": 70,
  "python Clone Graph": 133,
  "python Coin Change": 322,
  "python Coin Change II": 518,
  "python Combination Sum": 39,
  "python Combination Sum II": 40,
  "python Combination Sum IV": 377,
  "python Construct Binary Tree from Preorder and Inorder Traversal": 105,
  "python Container With Most Water": 11,
  "python Contains Duplicate": 217,
  "python Count Good Nodes In Binary Tree": 1448,
  "python Count Set Bits": 191,
  "python Counting Bits": 338,
  "python Course Schedule": 207,
  "python Course Schedule II": 210,
  "python Daily Temperatures": 739,
  "python Decode Ways": 91,
  "python Design Twitter": 355,
  "python Detect Squares": 2013,
  "python Diameter of Binary Tree": 543,
  "python Distinct Subsequences": 115,
  "python Edit Distance": 72,
  "python Encode and Decode Strings": 271,
  "python Evaluate Reverse Polish Notation": 150,
  "python Find Median from Data Stream": 295,
  "python Find Minimum in Rotated Sorted Array": 153,
  "python Frequency Count": 1207,
  "python Gas Station": 134,
  "python Generate Parentheses": 22,
  "python Graph DFS (Iterative)": 323,
  "python Graph DFS (Recursive)": 323,
  "python Graph Valid Tree": 261,
  "python Group Anagrams": 49,
  "python Hand of Straights": 846,
  "python Happy Number": 202,
  "python Hoare's Partition Scheme": 912,
  "python House Robber": 198,
  "python House Robber II": 213,
  "python Insert Interval": 57,
  "python Interleaving String": 97,
  "python Invert Binary Tree": 226,
  "python Jump Game": 55,
  "python Jump Game II": 45,
  "python K Closest Points to Origin": 973,
  "python Kadane's Algorithm": 53,
  "python Koko Eating Bananas": 875,
  "python Kth Largest Element In An Array": 215,
  "python Kth Largest Element In a Stream": 703,
  "python Kth Smallest Element in a BST": 230,
  "python Largest Rectangle In Histogram": 84,
  "python Last Stone Weight": 1046,
  "python Letter Combinations of a Phone Number": 17,
  "python Linked List Cycle Detection": 141,
  "python Linked List Traversal (Iterative)": 234,
  "python Linked List Traversal (Recursive)": 234,
  "python Lomuto Partition": 912,
  "python Longest Common Subsequence": 1143,
  "python Longest Consecutive Sequence": 128,
  "python Longest Increasing Path In a Matrix": 329,
  "python Longest Increasing Subsequence": 300,
  "python Longest Palindromic Substring": 5,
  "python Longest Repeating Character Replacement": 424,
  "python Longest Substring Without Repeating Characters": 3,
  "python Lowest Common Ancestor of a Binary Search Tree": 235,
  "python Matrix BFS": 1091,
  "python Matrix DFS (Iterative)": 200,
  "python Matrix DFS (Recursive)": 200,
  "python Max Area of Island": 695,
  "python Maximum Depth of Binary Tree": 104,
  "python Maximum Product Subarray": 152,
  "python Median of Two Sorted Arrays": 4,
  "python Meeting Rooms": 252,
  "python Meeting Rooms II": 253,
  "python Merge Intervals": 56,
  "python Merge K Sorted Lists": 23,
  "python Merge Sort": 912,
  "python Merge Triplets to Form Target Triplet": 1899,
  "python Merge Two Sorted Arrays": 88,
  "python Merge Two Sorted Lists": 21,
  "python Min Cost Climbing Stairs": 746,
  "python Min Cost to Connect All Points": 1584,
  "python Min Heap": 703,
  "python Min Stack": 155,
  "python Minimum Interval to Include Each Query": 1851,
  "python Minimum Window Substring": 76,
  "python Missing Number": 268,
  "python Monotonic Stack": 496,
  "python Most Frequent Element": 169,
  "python Multiply Strings": 43,
  "python N Queens": 51,
  "python Network Delay Time": 743,
  "python Non-overlapping Intervals": 435,
  "python Number of Connected Components in an Undirected Graph": 323,
  "python Number of Islands": 200,
  "python Pacific Atlantic Water Flow": 417,
  "python Palindrome Partitioning": 131,
  "python Palindromic Substrings": 647,
  "python Partition Equal Subset Sum": 416,
  "python Partition Labels": 763,
  "python Permutations": 46,
  "python Plus One": 66,
  "python Pow(x, n)": 50,
  "python Product of Array Except Self": 238,
  "python Queue from Two Stacks": 232,
  "python Quick Sort": 912,
  "python Range Sum Query": 303,
  "python Reconstruct Itinerary": 332,
  "python Redundant Connection": 684,
  "python Regular Expression Matching": 10,
  "python Remove Nth Node From End of List": 19,
  "python Reorder List": 143,
  "python Reverse Bits": 190,
  "python Reverse Integer": 7,
  "python Reverse Linked List (Iterative)": 206,
  "python Reverse Linked List (Recursive)": 206,
  "python Rotate Image": 48,
  "python Rotting Oranges": 994,
  "python Same Tree": 100,
  "python Search a 2D Matrix": 74,
  "python Search in Rotated Sorted Array": 33,
  "python Serialize and Deserialize Binary Tree": 297,
  "python Set Matrix Zeroes": 73,
  "python Single Number XOR": 136,
  "python Sliding Window Max Sum": 2461,
  "python Spiral Matrix": 54,
  "python Subsets": 78,
  "python Subsets II": 90,
  "python Subtree of Another Tree": 572,
  "python Sum of Two Integers": 371,
  "python Surrounded Regions": 130,
  "python Swim In Rising Water": 778,
  "python Target Sum": 494,
  "python Task Scheduler": 621,
  "python Time Based Key-Value Store": 981,
  "python Top K Frequent Elements": 347,
  "python Topological Sort": 210,
  "python Trapping Rain Water": 42,
  "python Trie": 208,
  "python Two Pointer Remove Duplicates": 26,
  "python Two Sum": 1,
  "python Two Sum II - Input Array Is Sorted": 167,
  "python Union Find": 684,
  "python Unique Paths": 62,
  "python Valid Anagram": 242,
  "python Valid Palindrome": 125,
  "python Valid Parentheses": 20,
  "python Valid Parenthesis String": 678,
  "python Valid Sudoku": 36,
  "python Validate Binary Search Tree": 98,
  "python Walls And Gates": 286,
  "python Word Break": 139,
  "python Word Ladder": 127,
  "python Word Search": 79,
  "python Word Search II": 212,
};

/** Resolve a seed kata's LeetCode number, or null if it is not a LeetCode problem. */
export function leetcodeNumberFor(kata: Pick<SeedKata, "name" | "language">): number | null {
  return LEETCODE_NUMBERS[lcKey(kata.language, kata.name)] ?? null;
}
