import type { SeedKata } from "../types/editor";

/** Lookup key for LEETCODE_NUMBERS: a plain, greppable space between language
 * and name. */
function lcKey(language: string, name: string): string {
  return `${language} ${name}`;
}

/**
 * LeetCode problem numbers for seed katas, keyed by `${language} ${name}`.
 *
 * Authoritative source for a kata's LeetCode number — the DB leetcode_number
 * column and the list-view badge both derive from it. Katas that are not
 * LeetCode problems (algorithm drills, runner error fixtures) are intentionally
 * absent and resolve to null.
 *
 * When adding a LeetCode-based seed kata, add its number here too.
 */
export const LEETCODE_NUMBERS: Record<string, number> = {
  "javascript 3Sum": 15,
  "javascript Add Two Numbers": 2,
  "javascript Balanced Parentheses": 20,
  "javascript Best Time to Buy and Sell Stock": 121,
  "javascript Binary Search": 704,
  "javascript Binary Search Find First": 34,
  "javascript Binary Search Find Last": 34,
  "javascript Binary Tree BFS": 102,
  "javascript Build Adjacency List": 133,
  "javascript Build Prefix Sum": 1480,
  "javascript Climbing Stairs": 70,
  "javascript Copy List with Random Pointer": 138,
  "javascript Count Set Bits": 191,
  "javascript DFS Inorder Traversal": 94,
  "javascript DFS Postorder Traversal": 145,
  "javascript DFS Preorder Traversal": 144,
  "javascript Find the Duplicate Number": 287,
  "javascript FizzBuzz": 412,
  "javascript Frequency Count": 1207,
  "javascript Graph DFS": 323,
  "javascript Kadane's Algorithm": 53,
  "javascript Linked List Cycle": 141,
  "javascript Linked List Traversal": 234,
  "javascript Lomuto Partition": 912,
  "javascript Longest Common Subsequence": 1143,
  "javascript Matrix BFS": 1091,
  "javascript Matrix DFS": 200,
  "javascript Merge Intervals": 56,
  "javascript Merge Sort": 912,
  "javascript Merge Sorted Arrays": 88,
  "javascript Min Heap": 703,
  "javascript Monotonic Stack": 496,
  "javascript Most Frequent Element": 347,
  "javascript Permutation in String": 567,
  "javascript Permutations": 46,
  "javascript Queue from Stacks": 232,
  "javascript Quick Sort": 912,
  "javascript Range Sum Query": 303,
  "javascript Remove Nth Node From End of List": 19,
  "javascript Reverse Linked List (Iterative)": 206,
  "javascript Reverse Linked List (Recursive)": 206,
  "javascript Rotate Image": 48,
  "javascript Search a 2D Matrix": 74,
  "javascript Single Number XOR": 136,
  "javascript Sliding Window Max Sum": 2461,
  "javascript Subsets": 78,
  "javascript Time Based Key-Value Store": 981,
  "javascript Topological Sort": 210,
  "javascript Trie": 208,
  "javascript Two Pointer Remove Dupes": 26,
  "javascript Two Sum": 1,
  "javascript Two Sum II - Input Array Is Sorted": 167,
  "javascript Union Find": 684,
  "python 3Sum": 15,
  "python Add and Search Word": 211,
  "python Alien Dictionary": 269,
  "python Balanced Binary Tree": 110,
  "python Balanced Parentheses": 20,
  "python Best Time to Buy and Sell Stock": 121,
  "python Best Time to Buy and Sell Stock With Cooldown": 309,
  "python Binary Search (Iterative)": 704,
  "python Binary Search (Recursive)": 704,
  "python Binary Search Find First": 34,
  "python Binary Search Find Last": 34,
  "python Binary Tree BFS": 102,
  "python Binary Tree Inorder (Iterative)": 94,
  "python Binary Tree Inorder (Recursive)": 94,
  "python Binary Tree Level Order Traversal": 102,
  "python Binary Tree Maximum Path Sum": 124,
  "python Binary Tree Postorder (Iterative)": 145,
  "python Binary Tree Postorder (Recursive)": 145,
  "python Binary Tree Preorder (Iterative)": 144,
  "python Binary Tree Preorder (Recursive)": 144,
  "python Binary Tree Right Side View": 199,
  "python Build Adjacency List": 133,
  "python Build Prefix Sum": 1480,
  "python Burst Balloons": 312,
  "python Car Fleet": 853,
  "python Cheapest Flights Within K Stops": 787,
  "python Climbing Stairs (Iterative)": 70,
  "python Climbing Stairs (Recursive)": 70,
  "python Clone Graph": 133,
  "python Coin Change": 322,
  "python Coin Change II": 518,
  "python Combination Sum": 39,
  "python Combination Sum II": 40,
  "python Combination Sum IV": 377,
  "python Construct Binary Tree from Preorder and Inorder Traversal": 105,
  "python Container With Most Water": 11,
  "python Contains Duplicate": 217,
  "python Count Good Nodes In Binary Tree": 1448,
  "python Count Set Bits": 191,
  "python Counting Bits": 338,
  "python Course Schedule": 207,
  "python Course Schedule II": 210,
  "python Daily Temperatures": 739,
  "python Decode Ways": 91,
  "python Delete and Earn": 740,
  "python Design Twitter": 355,
  "python Detect Squares": 2013,
  "python Diameter of Binary Tree": 543,
  "python Distinct Subsequences": 115,
  "python Edit Distance": 72,
  "python Encode and Decode Strings": 271,
  "python Evaluate Reverse Polish Notation": 150,
  "python Fibonacci Number": 509,
  "python Find Median from Data Stream": 295,
  "python Find Minimum in Rotated Sorted Array": 153,
  "python Frequency Count": 1207,
  "python Gas Station": 134,
  "python Generate Parentheses": 22,
  "python Graph DFS (Iterative)": 323,
  "python Graph DFS (Recursive)": 323,
  "python Graph Valid Tree": 261,
  "python Group Anagrams": 49,
  "python Hand of Straights": 846,
  "python Happy Number": 202,
  "python Hoare's Partition Scheme": 912,
  "python House Robber": 198,
  "python House Robber II": 213,
  "python Insert Interval": 57,
  "python Interleaving String": 97,
  "python Invert Binary Tree": 226,
  "python Jump Game": 55,
  "python Jump Game II": 45,
  "python K Closest Points to Origin": 973,
  "python Kadane's Algorithm": 53,
  "python Koko Eating Bananas": 875,
  "python Kth Largest Element In An Array": 215,
  "python Kth Largest Element In a Stream": 703,
  "python Kth Smallest Element in a BST": 230,
  "python Largest Rectangle In Histogram": 84,
  "python Last Stone Weight": 1046,
  "python Letter Combinations of a Phone Number": 17,
  "python Linked List Cycle Detection": 141,
  "python Linked List Traversal (Iterative)": 234,
  "python Linked List Traversal (Recursive)": 234,
  "python Lomuto Partition": 912,
  "python Longest Common Subsequence": 1143,
  "python Longest Consecutive Sequence": 128,
  "python Longest Increasing Path In a Matrix": 329,
  "python Longest Increasing Subsequence": 300,
  "python Longest Palindromic Subsequence": 516,
  "python Longest Palindromic Substring": 5,
  "python Longest Repeating Character Replacement": 424,
  "python Longest Substring Without Repeating Characters": 3,
  "python Lowest Common Ancestor of a Binary Search Tree": 235,
  "python Matrix BFS": 1091,
  "python Matrix DFS (Iterative)": 200,
  "python Matrix DFS (Recursive)": 200,
  "python Max Area of Island": 695,
  "python Maximum Depth of Binary Tree": 104,
  "python Maximum Length of Repeated Subarray": 718,
  "python Maximum Product Subarray": 152,
  "python Median of Two Sorted Arrays": 4,
  "python Meeting Rooms": 252,
  "python Meeting Rooms II": 253,
  "python Merge Intervals": 56,
  "python Merge K Sorted Lists": 23,
  "python Merge Sort": 912,
  "python Merge Triplets to Form Target Triplet": 1899,
  "python Merge Two Sorted Arrays": 88,
  "python Merge Two Sorted Lists": 21,
  "python Min Cost Climbing Stairs": 746,
  "python Min Cost to Connect All Points": 1584,
  "python Min Heap": 703,
  "python Min Stack": 155,
  "python Minimum Interval to Include Each Query": 1851,
  "python Minimum Path Sum": 64,
  "python Minimum Window Substring": 76,
  "python Missing Number": 268,
  "python Monotonic Stack": 496,
  "python Most Frequent Element": 169,
  "python Multiply Strings": 43,
  "python N Queens": 51,
  "python N-th Tribonacci Number": 1137,
  "python Network Delay Time": 743,
  "python Non-overlapping Intervals": 435,
  "python Number of Connected Components in an Undirected Graph": 323,
  "python Number of Islands": 200,
  "python Pacific Atlantic Water Flow": 417,
  "python Palindrome Partitioning": 131,
  "python Palindromic Substrings": 647,
  "python Partition Equal Subset Sum": 416,
  "python Partition Labels": 763,
  "python Perfect Squares": 279,
  "python Permutations": 46,
  "python Plus One": 66,
  "python Pow(x, n)": 50,
  "python Product of Array Except Self": 238,
  "python Queue from Two Stacks": 232,
  "python Quick Sort": 912,
  "python Range Sum Query": 303,
  "python Reconstruct Itinerary": 332,
  "python Redundant Connection": 684,
  "python Regular Expression Matching": 10,
  "python Remove Nth Node From End of List": 19,
  "python Reorder List": 143,
  "python Reverse Bits": 190,
  "python Reverse Integer": 7,
  "python Reverse Linked List (Iterative)": 206,
  "python Reverse Linked List (Recursive)": 206,
  "python Rotate Image": 48,
  "python Rotting Oranges": 994,
  "python Same Tree": 100,
  "python Search a 2D Matrix": 74,
  "python Search in Rotated Sorted Array": 33,
  "python Serialize and Deserialize Binary Tree": 297,
  "python Set Matrix Zeroes": 73,
  "python Single Number XOR": 136,
  "python Sliding Window Max Sum": 2461,
  "python Spiral Matrix": 54,
  "python Subsets": 78,
  "python Subsets II": 90,
  "python Subtree of Another Tree": 572,
  "python Sum of Two Integers": 371,
  "python Surrounded Regions": 130,
  "python Swim In Rising Water": 778,
  "python Target Sum": 494,
  "python Task Scheduler": 621,
  "python Time Based Key-Value Store": 981,
  "python Top K Frequent Elements": 347,
  "python Topological Sort": 210,
  "python Trapping Rain Water": 42,
  "python Trie": 208,
  "python Two Pointer Remove Duplicates": 26,
  "python Two Sum": 1,
  "python Two Sum II - Input Array Is Sorted": 167,
  "python Union Find": 684,
  "python Triangle": 120,
  "python Unique Paths": 62,
  "python Unique Paths II": 63,
  "python Valid Anagram": 242,
  "python Valid Palindrome": 125,
  "python Valid Parentheses": 20,
  "python Valid Parenthesis String": 678,
  "python Valid Sudoku": 36,
  "python Validate Binary Search Tree": 98,
  "python Walls And Gates": 286,
  "python Word Break": 139,
  "python Word Ladder": 127,
  "python Word Search": 79,
  "python Word Search II": 212,
};

/** Resolve a seed kata's LeetCode number, or null if it is not a LeetCode problem. */
export function leetcodeNumberFor(kata: Pick<SeedKata, "name" | "language">): number | null {
  return LEETCODE_NUMBERS[lcKey(kata.language, kata.name)] ?? null;
}

/**
 * Canonical LeetCode titleSlug for each problem number we reference, keyed by
 * problem number (language-independent). Combine with LEETCODE_NUMBERS to build
 * a problem URL. Contains only the numbers actually used by LEETCODE_NUMBERS.
 *
 * Generated from LeetCode's public problem list
 * (https://leetcode.com/api/problems/all/): frontend_question_id -> title_slug,
 * filtered to our used numbers. Sorted by number ascending.
 */
export const LEETCODE_SLUGS: Record<number, string> = {
  1: "two-sum",
  2: "add-two-numbers",
  3: "longest-substring-without-repeating-characters",
  4: "median-of-two-sorted-arrays",
  5: "longest-palindromic-substring",
  7: "reverse-integer",
  10: "regular-expression-matching",
  11: "container-with-most-water",
  15: "3sum",
  17: "letter-combinations-of-a-phone-number",
  19: "remove-nth-node-from-end-of-list",
  20: "valid-parentheses",
  21: "merge-two-sorted-lists",
  22: "generate-parentheses",
  23: "merge-k-sorted-lists",
  26: "remove-duplicates-from-sorted-array",
  33: "search-in-rotated-sorted-array",
  34: "find-first-and-last-position-of-element-in-sorted-array",
  36: "valid-sudoku",
  39: "combination-sum",
  40: "combination-sum-ii",
  42: "trapping-rain-water",
  43: "multiply-strings",
  45: "jump-game-ii",
  46: "permutations",
  48: "rotate-image",
  49: "group-anagrams",
  50: "powx-n",
  51: "n-queens",
  53: "maximum-subarray",
  54: "spiral-matrix",
  55: "jump-game",
  56: "merge-intervals",
  57: "insert-interval",
  62: "unique-paths",
  63: "unique-paths-ii",
  64: "minimum-path-sum",
  120: "triangle",
  66: "plus-one",
  70: "climbing-stairs",
  72: "edit-distance",
  73: "set-matrix-zeroes",
  74: "search-a-2d-matrix",
  76: "minimum-window-substring",
  78: "subsets",
  79: "word-search",
  84: "largest-rectangle-in-histogram",
  88: "merge-sorted-array",
  90: "subsets-ii",
  91: "decode-ways",
  94: "binary-tree-inorder-traversal",
  97: "interleaving-string",
  98: "validate-binary-search-tree",
  100: "same-tree",
  102: "binary-tree-level-order-traversal",
  104: "maximum-depth-of-binary-tree",
  105: "construct-binary-tree-from-preorder-and-inorder-traversal",
  110: "balanced-binary-tree",
  115: "distinct-subsequences",
  121: "best-time-to-buy-and-sell-stock",
  124: "binary-tree-maximum-path-sum",
  125: "valid-palindrome",
  127: "word-ladder",
  128: "longest-consecutive-sequence",
  130: "surrounded-regions",
  131: "palindrome-partitioning",
  133: "clone-graph",
  134: "gas-station",
  136: "single-number",
  138: "copy-list-with-random-pointer",
  139: "word-break",
  141: "linked-list-cycle",
  143: "reorder-list",
  144: "binary-tree-preorder-traversal",
  145: "binary-tree-postorder-traversal",
  150: "evaluate-reverse-polish-notation",
  152: "maximum-product-subarray",
  153: "find-minimum-in-rotated-sorted-array",
  155: "min-stack",
  167: "two-sum-ii-input-array-is-sorted",
  169: "majority-element",
  190: "reverse-bits",
  191: "number-of-1-bits",
  198: "house-robber",
  199: "binary-tree-right-side-view",
  200: "number-of-islands",
  202: "happy-number",
  206: "reverse-linked-list",
  207: "course-schedule",
  208: "implement-trie-prefix-tree",
  210: "course-schedule-ii",
  211: "design-add-and-search-words-data-structure",
  212: "word-search-ii",
  213: "house-robber-ii",
  215: "kth-largest-element-in-an-array",
  217: "contains-duplicate",
  226: "invert-binary-tree",
  230: "kth-smallest-element-in-a-bst",
  232: "implement-queue-using-stacks",
  234: "palindrome-linked-list",
  235: "lowest-common-ancestor-of-a-binary-search-tree",
  238: "product-of-array-except-self",
  242: "valid-anagram",
  252: "meeting-rooms",
  253: "meeting-rooms-ii",
  261: "graph-valid-tree",
  268: "missing-number",
  269: "alien-dictionary",
  271: "encode-and-decode-strings",
  279: "perfect-squares",
  286: "walls-and-gates",
  287: "find-the-duplicate-number",
  295: "find-median-from-data-stream",
  297: "serialize-and-deserialize-binary-tree",
  300: "longest-increasing-subsequence",
  303: "range-sum-query-immutable",
  309: "best-time-to-buy-and-sell-stock-with-cooldown",
  312: "burst-balloons",
  322: "coin-change",
  323: "number-of-connected-components-in-an-undirected-graph",
  329: "longest-increasing-path-in-a-matrix",
  332: "reconstruct-itinerary",
  338: "counting-bits",
  347: "top-k-frequent-elements",
  355: "design-twitter",
  371: "sum-of-two-integers",
  377: "combination-sum-iv",
  412: "fizz-buzz",
  416: "partition-equal-subset-sum",
  417: "pacific-atlantic-water-flow",
  424: "longest-repeating-character-replacement",
  435: "non-overlapping-intervals",
  494: "target-sum",
  496: "next-greater-element-i",
  509: "fibonacci-number",
  516: "longest-palindromic-subsequence",
  518: "coin-change-ii",
  543: "diameter-of-binary-tree",
  567: "permutation-in-string",
  572: "subtree-of-another-tree",
  621: "task-scheduler",
  647: "palindromic-substrings",
  678: "valid-parenthesis-string",
  684: "redundant-connection",
  695: "max-area-of-island",
  703: "kth-largest-element-in-a-stream",
  704: "binary-search",
  718: "maximum-length-of-repeated-subarray",
  739: "daily-temperatures",
  740: "delete-and-earn",
  743: "network-delay-time",
  746: "min-cost-climbing-stairs",
  763: "partition-labels",
  778: "swim-in-rising-water",
  787: "cheapest-flights-within-k-stops",
  846: "hand-of-straights",
  853: "car-fleet",
  875: "koko-eating-bananas",
  912: "sort-an-array",
  973: "k-closest-points-to-origin",
  981: "time-based-key-value-store",
  994: "rotting-oranges",
  1046: "last-stone-weight",
  1091: "shortest-path-in-binary-matrix",
  1137: "n-th-tribonacci-number",
  1143: "longest-common-subsequence",
  1207: "unique-number-of-occurrences",
  1448: "count-good-nodes-in-binary-tree",
  1480: "running-sum-of-1d-array",
  1584: "min-cost-to-connect-all-points",
  1851: "minimum-interval-to-include-each-query",
  1899: "merge-triplets-to-form-target-triplet",
  2013: "detect-squares",
  2461: "maximum-sum-of-distinct-subarrays-with-length-k",
};

/** Resolve a LeetCode problem number to its canonical titleSlug, or null. */
export function leetcodeSlugFor(n: number): string | null {
  return LEETCODE_SLUGS[n] ?? null;
}

/** Resolve a seed kata to its LeetCode problem URL, or null if it is not a
 * LeetCode problem (or has no known slug). */
export function leetcodeUrlFor(kata: Pick<SeedKata, "name" | "language">): string | null {
  const n = leetcodeNumberFor(kata);
  if (n == null) return null;
  const slug = leetcodeSlugFor(n);
  return slug ? `https://leetcode.com/problems/${slug}/` : null;
}

